package frc.components;

public class Events
{
    public static enum ShuttleEvent
    {
        NONE,
        INTAKE_CARGO_CAN_BE_SHUTTLED_SENSOR_ACTIVATES,
        INTAKE_CARGO_CAN_BE_SHUTTLED_SENSOR_DEACTIVATES,
        STAGE_ONE_FULL_SENSOR_ACTIVATES,
        STAGE_ONE_FULL_SENSOR_DEACTIVATES,
        STAGE_TWO_FULL_SENSOR_ACTIVATES,
        STAGE_TWO_FULL_SENSOR_DEACTIVATES,
        SHOOT_IS_CALLED;
    }
}
